### ISSUE TITLE
UTXOs are truncated in Snowball

### ISSUE THREAD

**Issue by rtsisyk** [stegos/stegos#1230]
PaymentOutput is encoded using protobuf. Protobuf can produce messages of variable size even for the same structure. For example, int64 can have a maximum data length of 10 bytes.

Current implementation of Snowball takes one random UTXO and saves it size to self.serialized_utxo_size:

https://github.com/stegos/stegos/blob/949293cb3af6dce46f1bf05a3419a417ccc59be7/wallet/src/snowball/mod.rs#L281
https://github.com/stegos/stegos/blob/949293cb3af6dce46f1bf05a3419a417ccc59be7/wallet/src/snowball/mod.rs#L1281-L1290

This value is used to truncate input buffer:

https://github.com/stegos/stegos/blob/949293cb3af6dce46f1bf05a3419a417ccc59be7/wallet/src/snowball/mod.rs#L1477
https://github.com/stegos/stegos/blob/949293cb3af6dce46f1bf05a3419a417ccc59be7/wallet/src/snowball/mod.rs#L2104-L2116

Please find some solution to create fixed-size UTXO for Dicemix.

**Comment by dbmcclain** [comment]
Checking the structure of PaymentOutput, there are no simple scalar slots like i64. Everything, with the possible exception of locked_timestamp is serialized to a fixed number of unsigned bytes.

locked_timestamp is indicated to be of type Option(Timestamp), so I would not expect this field to have a constant size, even if an encoded timestamp were always a known fixed size. A preferable encoding should have an indicator bit for Option (Some, None), followed by a fixed number of unsigned bytes. And for efficiency in DiceMix, and space conservation in the blockchain, a short binary encoding of Timestamp would be preferred over a longer human readable string format.

DiceMix is used to relay all kinds of different shared values in cloaked form. But, whatever is being shared, must have constant size so that it can be sliced into a fixed number of DiceMix matrix cells. DiceMix cannot know what objects you are sharing, just that their length is some fixed amount for each separate DiceMix session.

So it is not up to DiceMix to make this decision, but rather, client code calling DiceMix must arrange for all items to have the same length.

So it appears that the solution is to enforce a fixed-length binary encoding of Option(Timestamp) for PaymentOutput records being shared through DiceMix in Snowball.

**Comment by dbmcclain** [comment]
As an alternative, to code around a rather loose specification and serialization in our existing code base, Snowball can ask that the UTXO be converted into a fixed-length unsigned byte array. This will have PaymentOutput provide a separate serialization construct, apart from Protobufs, that produces what we need.

**Comment by dbmcclain** [comment]
okay... it took me a while to shift from Lisp mindset. I understand how serialization optimizes by varying its output. That cannot be used by Snowball. Instead, I am providing a fixed-length encoding for PaymentOutput in Snowball and associated libs.

**Comment by rtsisyk** [comment]
Fixed
