### ISSUE TITLE
Network Design

### ISSUE THREAD

**Issue by rtsisyk** [stegos/stegos#49]

**Comment by echupriyanov** [comment]
# Stegos networking

## Preface

We are going to reuse architecture design of [LibP2P](https://libp2p.io), in particular its [Rust implementation](https://github.com/libp2p/rust-libp2p)

## Address formats

LibP2P proposes use of `multiaddr` format - https://github.com/multiformats/multiaddr

Rust implementation - https://github.com/libp2p/rust-libp2p/tree/master/misc/multiaddr

## Hash representation

Multihash specification - https://github.com/multiformats/multihash

Rust implementation - https://github.com/libp2p/rust-libp2p/tree/master/misc/multihash

## Public Keys

`rust-libp2p` has generic `PublicKey` abstraction. At this moment following types are supported:

* RSA (2048-bit)
* Ed25519
* Secp256k1

## Peer Identity

In `rust-libp2p` design peers are represented by private/public key pair.
Peers IDs are represented by SHA2-256 hash of their public keys.

## Transport layer

Though `rust-libp2p` provides both unencrypted and encrypted transport, I propose to make encrypted communications mandatory. Besides obvious benefits of encryption, `secio` implpementation also provides as with remote Peer ID, since its key pair is used for encryption and public key is transmitted during initial handshake.

The same key can be used later in NIKE.

*Question: which key type is most appropriate here?*

## Middle layer

In our networking model, we need two kinds communications:

* Broadcast (Bulletin board) - messages should be delivered to and processed by all nodes in the network
* Direct peer-to-peer commincations - low-level mechanisms, responsible for smooth network operation:
  * Peer Discovery
  * Peer liveness
  * ???

For the broadcasting protocol we can reuse existing `rust-libp2p` [floodsub implmentation](https://github.com/libp2p/rust-libp2p/tree/master/protocols/floodsub)

For the Peer Discovery there is no exisiting complete implementation, so it had to be designed and implemented by our team and is subject for separate RFC.

**Comment by echupriyanov** [comment]
# Direct peer-to-peer communications

## Preface

The communication model is mostly taken from [Grin project](https://github.com/mimblewimble/grin). The main difference is that each connection consists of at least 2 substreams:

* Broadcasting (floodsub)
* Network control substream

Here is higher-level description of control protocol.

## Bootstrap

* When new node started, it tries to connect to preconfigured set of "bootstrap" nodes.

* When new outgoing connection is established, node sends request for all known peers.

* "Seed" loop started

## "Seed" loop

* Every N (20 for Grin) seconds the node checks count of currently connected peers. If count is less then M (8 for Grin), then:
  * node sends request for all known peers to all connected nodes
  * initiates connections to known not-connected peers for upto K (25 for Grin) total connected peers

* Every L (10 for Grin) seconds send pings to all connected peers.

* Run cleanup on all known peers (dropping disconnected and silent peers, etc.)

## Additional details

* Peer lists are received asynchronously and stored in PeerStore, which is periodically persisted for use after node restart

* Following `rust-libp2p` design, we are going to use `protobuf` for on-wire encoding.
