### ISSUE TITLE
Service Awards

### ISSUE THREAD

**Issue by rtsisyk** [stegos/stegos#54]

**Comment by vlebedev** [comment]
Jackpot logic has been finalized:

- 1/3 of all block rewards goes to the Jackpot 
- Users spend coins to buy lottery tickets
- The payment for each ticket is added to the pot
- Each ticket has 7 numbers specified by the user: 
  - The range of the first 6 numbers is 1 -- 33 and the last number 1 -- 16
- A 7-number winning sequence is generated for each lottery run
- A tier of prizes for guessing the numbers right: 
 - 1st prize. Matching all the 7 numbers
 - 2nd prize. Guessing the first 6 numbers correctly
 - 3rd prize. Guessing any 5 numbers, plus the 7th
 - 4th prize. Any 5 numbers out of first 6, or 4 numbers plus the 7th
 - 5th prize. Any 4 numbers out of first 6, or 3 numbers plus the 7th 
 - 6th prize. Any 2 numbers out of first 6 plus 7th, or any 1 number out of first 6 + 7th, or just 7th (the price of the ticket back)
- If the pot is not won then it keeps growing 
- The jackpot lottery runs at a random time 
- Only tickets bought 1 week or more in advance participate in the draw

Algorithm for calculating prize sizes will follow.

**Comment by vlebedev** [comment]
### Implementation details:

 - We well need a new slot in block header - `Jackpot`, containing non-negative integer in the range of `[0..2^64]`
 - `Jackpot` slot should be accounted for in the monetary balance equation
 - Each block, 1/3 of the block reward must go into `Jackpot`, i.e. contents of `Jackpot` should be incremented with the value of 1/3 of the block reward
 - Jackpot tickets must be implemented via special type of UTXO (`Lottery UTXO`):
   - `Lottery UTXO` is a **public UTXO**, meaning it has no cloaking on public key and amount
   - `pubkey` slot in the `Lottery UTXO` must contain an uncloaked public key of the user that buys the ticket, this pubkey will be used for prize payout later on
   - `amount` slot in the `Lottery UTXO` must contain an uncloaked amount equal to *the cost of the ticket* (**TBD**)
   - Encrypted payload in `Lottery UTXO` should be unencrypted and it should contain a `lucky number`, a sequence of 7 numbers as defined in the comment above
   - `Lottery UTXO` should be created by a wallet, using VS transaction **ONLY** (because otherwise the relationship between anonymous UTXOs in inputs and public UTXO containing user's uncloaked public key may be established)
   - `Lottery UTXO` must be spendable only by a leader of validators group only, which means it cannot be used in any inputs of any transactions (VS or not)
 - Jackpot run is triggered via some formula based on the previous block random value (for example, it can be triggered if random value has two digits 8 at the end, or something similar, **TBD**)
 - When Jackpot is triggered, the leader of the current block should pick up all unspent `Lottery UTXOs` which associated with blocks older than one week and use them for the lottery
 - All used `Lottery UTXOs` must be referenced in inputs of the current block
 - `Jackpot` slot in the current block should be incremented with a sum of all used `Lottery UTXOs` amounts
 - Jackpot payouts, if any, must be placed as public UTXOs (with visible pubkeys and amounts) into current blocks' outputs
 - So, when the block will be sealed and broadcasted by the leader, all validators will be able to check if Jackpot prizes were assigned properly and all eligible lottery tickets were spent 

### Notes:

 - Anonymous UTXO: recipient pubkey and amount are cloaked
 - Confidential UTXO: only amount is cloaked
 - Public UTXO: nothing is cloaked

**Comment by rtsisyk** [comment]
Done
