### ISSUE TITLE
Wallet and API proposal

### ISSUE THREAD

**Issue by venticello** [stegos/stegos#766]
API:
1. Subscribe to Websocket notifications streams, like as [Binance](https://docs.binance.org/api-reference/dex-api/ws-connection.html)
ws://localhost:3145/node/ Block Added, Epoch Changed
ws://localhost:3145/wallet/ Balance Changed, Payment Received
and about transaction change state, for example, ValueShuffle Payment has state "value_shuffle_started", but I don't know when this transaction will complete.
2. +rest-api methods:
get last block number
get block by id or hash
get last N blocks
get trasaction by tx-hash

3. For an error response, I think need field "code"
4. Add to documentation description of data types
5. For single request-response use HTTP REST-API and [OpenAPI specification](https://swagger.io/specification/).
> Fewer network requests, easier to use and test.

Wallet:
1. Open/Lock wallet by password (encrypt/decrypt keys).
2. Generate new key-pairs and seed-phrases for recovery
3. Change the current wallet key.
4. Creates and signs a transaction, but no transfers it to network.
5. Send raw operations/transactions (Maybe bulk).
6. Change the payment fee.
> This is all you need to be able to use a cold wallet.

**Comment by rtsisyk** [comment]
Hi!

> Subscribe to Websocket notifications streams, like as Binance
ws://localhost:3145/node/ Block Added, Epoch Changed
ws://localhost:3145/wallet/ Balance Changed, Payment Received

Actually, "/node" and "/wallet" are ignored right now.

> and about transaction change state, for example, ValueShuffle Payment has state "value_shuffle_started", but I don't know when this transaction will complete.

That is the problem. We don't have tracking for regular transactions. Tracking of ValueShuffle's transactions is even mor complicated. I described in https://github.com/stegos/stegos/issues/796#issuecomment-486733664 that wallet actually don't track transaction status. We definitely want to fix it somehow, but still trying to find a proper way to do it. 

> +rest-api methods:
get last block number
get block by id or hash
get last N blocks
get trasaction by tx-hash

There is no REST API, only WebSocket API. Adding a parallel HTTP REST API infrastructure requires some extra time we don't have right now. Probably after the mainnet release.
 We can implement such RPC calls in WebSocket API instead. Is it enough?

> 1. Open/Lock wallet by password (encrypt/decrypt keys).
> 2. Generate new key-pairs and seed-phrases for recovery

This part is currently in the progress. Please wait for TestNet-6.

> 3. Change the current wallet key.

Do you mean "multiple wallets"?

> 4. Creates and signs a transaction, but no transfers it to network.

What is the purpose of this API? We don't store transactions in wallet (

> 5. Send raw operations/transactions (Maybe bulk).
 
API is already asynchronous. Please just push a bunch of request to WebSocket. 
The only limitation that currently wallet doesn't track transaction status and you need to wait for the next block in order to send the next transaction.

**Comment by venticello** [comment]
> get last block number
> get block by id or hash
> get last N blocks
> get trasaction by tx-hash
You still have to implement this for the block explorer.

> We can implement such RPC calls in WebSocket API instead. Is it enough?

You can do everything through the web sockets, but for me, this is something new.

> Do you mean "multiple wallets"?

Yes, I preferred to have several wallets or at least a few public addresses.

> What is the purpose of this API? We don't store transactions in wallet (

For me transaction = payment. The main feature is to be able to sign payment offline and send them from another device without having to use a private key.

**Comment by rtsisyk** [comment]
We published documentation for WebSocket API: https://docs.stegos.com/about/developers/api
