### ISSUE TITLE
Testnet can't sync

### ISSUE THREAD

**Issue by venticello** [stegos/stegos#788]
![image](https://user-images.githubusercontent.com/1232990/56637283-ec1b6000-6673-11e9-8da7-1daa61813b2f.png)
Lastest testnet release.
DB cleared before the start.
db pop block does not effect.

**Comment by rtsisyk** [comment]
Confirmed. Thanks for this report!

We investigated this problem on TestNet-5:

1. TestNet-4 had a bug that the second and subsequent view_changes in the same epoch may produce a block with invalid ViewChangeProof signature.
2. This bug has been detected and fixed during development of TestNet-5, see https://github.com/stegos/stegos/pull/771/commits/d0495d1ce9b5d54f6f7fafe7d3395a818fcc45fa commit.
3. During deploying TestNet-5 we decided to keep database from TestNet-5.
4. Unfortunately, TestNet-4 database already had broken block at height 55000.

**Comment by rtsisyk** [comment]
Due to fact that TestNet-5 is not actually compatible with TestNet-4, we decided to reset TestNet-5 database completely and start from the scratch. TestNet-5 will be restarted within 10-15 minutes. Please reset your local database (`rm -rf database/`) and try again in 10-15 min.

We apologize for any inconvenience caused by this problem. Our blockchain format is still in flux and it will be stabilized by MainNet-1 release. The next release (TestNet-6) will also forcibly check entire database on the start.

**Comment by rtsisyk** [comment]
Please us on Telegram to get tokens.

**Comment by venticello** [comment]
Thank you, everything is fine now.
