### ISSUE TITLE
Warnings after stake

### ISSUE THREAD

**Issue by venticello** [stegos/stegos#793]
![image](https://user-images.githubusercontent.com/1232990/56658509-76c78380-66a3-11e9-8354-7a6b6e2ddc23.png)

**Comment by vldm** [comment]
Thank you for your bug report!
Most of warnings in consensus module, probably should be ignored by user, concrete this warning tell us, that we have conflicts keyblocks in our networks, this is usually okay, because all node try to disclosure it's version of blockchain history.

But it is not good that we show so many warnings at user scree, so we should filter-out consensus warnings from log output by default.

**Comment by venticello** [comment]
Maybe add to the config configuration with the level of logs? So that ordinary users do not see what they can not influence. But at the same time write everything to the log file.

**Comment by rtsisyk** [comment]
Make sense.

**Comment by rtsisyk** [comment]
This problem has been fixed.
