### ISSUE TITLE
Websoket notification

### ISSUE THREAD

**Issue by venticello** [stegos/stegos#796]
I had 1050 coins, I sent 1000 for stake. (2 fee)
I receive 2 notifications, but "payment_received" does not logically correspond to reality, I just formed a new utxo.
```
{"notification":"payment_received","amount":48,"comment":""}
{"notification":"balance_changed","balance":48}
```

**Comment by rtsisyk** [comment]
What do you think about renaming this notification to "utxo_received" and adding "utxo_spent" counterpart?

**Comment by venticello** [comment]
I think the main thing is that the notifications are clearly understood. It would be great if the program could determine that the payment came from someone or this division of my payment. "balance_changed" is ok. But I don’t know what to do in programs with information about utxo. Now we need to think about how to make a convenient integration for exchanges so that deposits can be easily processed and identified.

**Comment by rtsisyk** [comment]
Currently we don't track transaction's status in the wallet. Wallet just create a new transaction and push it to the network. if transaction is valid (i.e has proper inputs, monetary balance and signature), it should be applied and included to the block sometime. Since this blockchain is untraceable, there is no reliable way to distinguish between your change and regular payment from third-party without tracking this information in the wallet. 

Tracking of transactions adds some extra state to the wallet which can't be stored in the blockchain. Currently there are no other databases in this system expected the blockchain database itself. We are considering different options how to handle pending transactions in a wallet. Probably we need to persist this state too. What do you think about it? 

Which kind of API will be convenient for integration for exchanges?

**Comment by venticello** [comment]
Today I researched a competitor, Beam, they have such a thing as "Payment proof verification"
[More info about Payment confirmation](https://github.com/BeamMW/beam/wiki/Payment-confirmation-(proof)#payment-confirmation)

**Comment by rtsisyk** [comment]
See https://docs.stegos.com/about/developers/api#transaction-tracking
